apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  containers:
  - image: nginx:1.15.11
    imagePullPolicy: IfNotPresent
    name: web
    ports:
    - containerPort: 80

